import type { RouteType } from "@/types"

export const routeMap = new Map<string, RouteType>([
  ["/sign-in", { type: "guest" }],
  ["/register", { type: "guest" }],
  ["/forgot-password", { type: "guest" }],
  ["/verify-email", { type: "guest" }],
  ["/new-password", { type: "guest" }],
  ["/", { type: "public" }],
  ["/docs", { type: "public" }],
  ["/documentation", { type: "public" }],
  ["/admin", { type: "public" }],
  ["/shop", { type: "public" }],
  ["/customer", { type: "public" }],
  ["/apps", { type: "public" }],
  ["/cards", { type: "public" }],
  ["/charts", { type: "public" }],
  ["/colors", { type: "public" }],
  ["/extended-ui", { type: "public" }],
  ["/forms", { type: "public" }],
  ["/icons", { type: "public" }],
  ["/pages", { type: "public" }],
  ["/tables", { type: "public" }],
  ["/typography", { type: "public" }],
  ["/ui", { type: "public" }],
  ["/dashboards", { type: "public" }],
])
